In [34]:
list = [1, 2, 3, 4, 5, 6, 7, 8,]

list(range(3,6))

TypeError: 'list' object is not callable

## Lambda

In [7]:
val = lambda a, b, c: a * b / c

In [61]:
labd = lambda a,c,u: a * c / u 

In [63]:
labd(2,3,4 )

1.5

In [9]:
val(3, 4, 4)

3.0

In [10]:
val = 'How are you doing'

In [14]:
val.title()

'How Are You Doing '

In [15]:
val.lower()

'how are you doing '

In [16]:
val.upper()

'HOW ARE YOU DOING '

In [17]:
var = [ 1, 2, 3, 4,5, 6,]

In [19]:
var.append(4)

In [20]:
var

[1, 2, 3, 4, 5, 6, 4]

In [21]:
var.append([2,4,5,6,])

In [23]:
var

[1, 2, 3, 4, 5, 6, 4, [2, 4, 5, 6]]

In [24]:
var.extend([5,6,7,8,9,0])

In [25]:
var

[1, 2, 3, 4, 5, 6, 4, [2, 4, 5, 6], 5, 6, 7, 8, 9, 0]

# POP METHOD AND COUNT METHOD

In [28]:
var.pop(4)

5

In [27]:
var

[1, 2, 3, 4, 5, 6, 4, [2, 4, 5, 6], 5, 6, 7, 8, 9]

In [29]:
var.pop(6)

[2, 4, 5, 6]

In [30]:
var

[1, 2, 3, 4, 6, 4, 5, 6, 7, 8, 9]

# count method 

In [31]:
var.count(4)

2

In [32]:
var.count(3)

1

In [33]:
var.count(0)

0

# dic method

In [2]:
New_dic = {'key1':5,'key2':6, 'key3':7, 'key4':8,}

In [4]:
New_dic.keys()

dict_keys(['key1', 'key2', 'key3', 'key4'])

In [5]:
New_dic.items()

dict_items([('key1', 5), ('key2', 6), ('key3', 7), ('key4', 8)])

In [6]:
New_dic.values()

dict_values([5, 6, 7, 8])

# Modules or library --- Numpy, random, scipy

In [8]:
import numpy as np 

In [12]:
np.array([2, 3, 4, 6, 7])

array([2, 3, 4, 6, 7])

In [13]:
np.array([2, 3, 4, 6, 7])> 5

array([False, False, False,  True,  True])

In [14]:
np.array([2, 3, 4, 6, 7])+ 2

array([4, 5, 6, 8, 9])

In [18]:
list = [2, 3, 4, 6, 7]

# creating a matric 

In [49]:
hayb = [2,4,5,6],[7,8,9,0,]

In [50]:
# # methond 1 , creating matric from list

# np.array(([2,4,5,6],[7,8,9,0]))


np.array(hayb)

array([[2, 4, 5, 6],
       [7, 8, 9, 0]])

In [45]:
# np.array.reshape(4, 4)



In [51]:
new_vect=np.array(hayb)

In [76]:
new_vect.reshape()

ValueError: cannot reshape array of size 8 into shape (4,4)

In [74]:
np.linspace( 2, 4, 5)

array([2. , 2.5, 3. , 3.5, 4. ])

In [68]:
len(lin)

50